import = ['solarized_dark.toml']

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "CommitMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "CommitMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CommitMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CommitMono Nerd Font Mono"
style = "regular"
