import = ["~/.config/alacritty/solarized_dark.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "hjkl"
style = "Bold"

[font.bold_italic]
family = "hjkl"
style = "Bold Italic"

[font.italic]
family = "hjkl"
style = "Italic"

[font.normal]
family = "hjkl"
style = "Regular"
