add_newline = false

format = """
[==>](red)$directory$git_branch$character
"""

[directory]
style = "#008080"
home_symbol = ""

[git_branch]
format = "[git:(([\\($branch\\)](red)))](#6DACFA)"

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
staged = '[++\($count\)](green)'
