import = ["solorized-dark.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"
[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"
[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Italic"
[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"
