import = ["~/.dotfiles/.config/icons.toml"] 

[directory]
format = "[-->](fg:green) [$path](fg:cyan) "

[git_branch]
format = "on [$symbol$branch]($style) [$branch](fg:green) "

[line_break]
disabled = true
